class Rotors:   #TODO: I MIGHT CHANGE THIS
    CommericialEnigmaRotors = [
        'DMTWSILRUYQNKFEJCAZBPGXOHV',
        'HQZGPJTMOBLNCIFDYAWVEUSRKX',
        'UQNTLSZFMREHDPXKIBVYGJCWOA'
    ]
    
    GermanRailway = [
        'JGDQOXUSCAMIFRVTPNEWKBLZYH',
        'NTZPSFBOKMWRCJDIVLAEYUXHGQ',
        'JVIUBHTCDYAKEQZPOSGXNRMWFL',
        'QYHOGNECVPUZTFDJAXWMKISRBL',
        'QWERTZUIOASDFGHJKPYXCVBNML'
    ]

    SwissK = [
        'PEZUOHXSCVFMTBGLRINQJWAYDK',
        'ZOUESYDKFWPCIQXHMVBLGNJRAT',
        'EHRVXGAOBQUSIMZFLYNWKTPDJC',
        'IMETCGFRAYSQBZXWLHKDVUPOJN',
        'QWERTZUIOASDFGHJKPYXCVBNML'
    ]

    M3M4 = [
        'EKMFLGDQVZNTOWYHXUSPAIBRCJ',
        'AJDKSIRUXBLHWTMCQGZNPYFVOE',
        'BDFHJLCPRTXVZNYEIWGAKMUSQO',
        'ESOVPZJAYQUIRHXLNFTGKDCMWB',
        'VZBRGITYUPSDNHLXAWMJQOFECK',
        'JPGVOUMFYQBENHZRDKASXLICTW',
        'NZJHGRCXMYSWBOUFAIVLPEKQDT',
        'FKQHTLXOCBJSPDZRAMEWNIUYGV'
    ]

    EnigmaI = [
        'LEYJVCNIXWPBQMDRTAKZGFUHOS',
        'FSOKANUERHMBTIYCWLQPZXVGJD',
        'EJMZALYXVBWFCRQUONTSPIKHGD',
        'YRUHQSLDPXNGOKMIEBFZCWVJAT',
        'FVPJIAOYEDRZXWGCTKUQSBNMHL',
        'ENKQAUYWJICOPBLMDXZVFTHRGS',
        'RDOBJNTKVEHMLFCWZAXGYIPSUQ',
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    ]