class Rotors:
    OddSet = [
        'FVPJIAOYEDRZXWGCTKUQSBNMHL',
        'QWERTZUIOASDFGHJKPYXCVBNML',
        'FKQHTLXOCBJSPDZRAMEWNIUYGV'
    ]

    EvenSet = [
        'JGDQOXUSCAMIFRVTPNEWKBLZYH',
        'PEZUOHXSCVFMTBGLRINQJWAYDK',
        'QYHOGNECVPUZTFDJAXWMKISRBL'
    ]

    CommericialEnigmaRotors = [
        'DMTWSILRUYQNKFEJCAZBPGXOHV',
        'HQZGPJTMOBLNCIFDYAWVEUSRKX',
        'UQNTLSZFMREHDPXKIBVYGJCWOA'
    ]